# Generated by Django 3.1.2 on 2020-10-25 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20201023_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='kind',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='description',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.category'),
        ),
    ]
