# Generated by Django 3.1.2 on 2020-10-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20201025_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.FileField(blank=True, upload_to='images/menu'),
        ),
    ]
